stages:
  - test
  - release
default:
  image: registry.gitlab.com/etke.cc/base/build
variables:
  PLATFORMS: linux/arm64/v8,linux/amd64

lint:
  stage: test
  script:
    - just lint

unit:
  stage: test
  script:
    - just test

docker:
  stage: release
  only: ['main', 'tags']
  services: ['docker:dind']
  script:
    - just login docker
